zkports: "2888,3888"
envvs:
  ZOOCFG: zoo.cfg
  ZOOCFGDIR: /var/zookeeper
  ZOOPIDFILE: /opt/zookeeper/server.pid
  ZOO_LOG_DIR: /opt/zookeeper/logs
  ZOO_LOG4J_PROP: "INFO,CONSOLE"
installDir: "/opt/zookeeper"
zkconfig:
  tickTime: "1999"
  dataDir: "/var/lib/zookeeper/"
  clientPort: "2181"
  initLimit: "5"
  syncLimit: "2"
  dataLogDir: "/var/lib/zookeeper/"
