zkports: "2888,3888"
configFile: "/var/zookeeper/zoo.cfg"
logDir: /opt/zookeeper/logs
logProp: "INFO,CONSOLE"
pidFile: /opt/zookeeper/server.pid
installTo: "/opt/zookeeper"
zkconfig:
  tickTime: "1999"
  dataDir: "/var/lib/zookeeper/"
  clientPort: "2181"
  initLimit: "5"
  syncLimit: "2"
  dataLogDir: "/var/lib/zookeeper/"
